import { ScriptedScene, type ScriptFrame } from './ScriptedScene';

/**
 * Two pointers closing in on a sorted array until the pair sums to the target
 * — the block rail with `l`/`r` chips gliding between slots, scalar locals in
 * the readout beneath. Frames are generated by running the algorithm, so the
 * exhibit cannot drift from what the code would actually do.
 */
const NUMS = [1, 3, 4, 6, 8, 11];
const TARGET = 10;

function twoPointerFrames(): ScriptFrame[] {
  const frames: ScriptFrame[] = [];
  let l = 0;
  let r = NUMS.length - 1;
  while (l < r) {
    const sum = NUMS[l]! + NUMS[r]!;
    const cmp = sum === TARGET ? '=' : sum < TARGET ? '<' : '>';
    frames.push({
      scene: {
        kind: 'array',
        items: NUMS,
        pointers: [
          { name: 'l', index: l },
          { name: 'r', index: r },
        ],
      },
      readout: [
        ['target', String(TARGET)],
        ['nums[l]+nums[r]', `${sum} ${cmp}`],
      ],
    });
    if (sum === TARGET) break;
    if (sum < TARGET) l++;
    else r--;
  }
  return frames;
}

const FRAMES = twoPointerFrames();

export function ArrayScanDemo() {
  return <ScriptedScene frames={FRAMES} height={210} fallback={<ArrayScanFlat />} />;
}

/** The 2D exhibit, kept for reduced motion and machines without WebGL.
 *  Motion is entirely CSS (see site.css) and pauses under reduced motion. */
export function ArrayScanFlat() {
  return (
    <div className="d-array">
      <div className="d-row">
        {[2, 7, 11, 15].map((v, i) => (
          <span className="d-col" key={i}>
            <span className={`d-cell${i === 1 ? ' d-hit' : ''}`}>{v}</span>
            <span className="d-idx">{i}</span>
          </span>
        ))}
        <span className="d-ptr d-ptr-i">i</span>
        <span className="d-ptr d-ptr-j">j</span>
      </div>
      <div className="d-readout">
        <span className="d-chip">
          target<b>9</b>
        </span>
        <span className="d-chip">
          nums[i]+nums[j]<b className="d-sum">9</b>
        </span>
      </div>
    </div>
  );
}
